name: spring-boot-docker deployment

on: workflow_dispatch

jobs:
  unit_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Run unit test with gradle
        run: ./gradlew bootJar
      - name: store docker image cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build docker image
        run: docker build -t spring-bootjar-docker .

